### ISSUE TITLE
Javascript

### ISSUE THREAD

**Issue by nicohvi** [nplol/marvin#2]
Skriv om til javascript (:cry:)

**Comment by vongohren** [comment]
Why?

**Comment by vongohren** [comment]
Spør en gang til jeg, why @nicohvi ?

**Comment by nicohvi** [comment]
Fordi coffeescript blir unødvendig når EcmaScript 2015 blir vanlig.

**Comment by vongohren** [comment]
Men det blir jo ikke nødvendig, du kan jo bare skrive javascript scripts for å utvide.

**Comment by nicohvi** [comment]
Åja, ser denne var litt dårlig ordlagt - mente å skrive om koden vår (noracist osv.) til javascript.
